version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Install dependencies
          # These versions are the latest ones available in piwheels
          command: pip install pytest numpy==1.24.2 scipy==1.8.1
      - run:
          name: Run tests
          command: pytest tests/

workflows:
  version: 2
  build_and_test:
    jobs:
      - build

